version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mssql:
    driver: ${VOLUMES_DRIVER}

services:

  ### MS SQL ###########################################
    mssql:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: mssql
      volumes:
      - ./data/mssql-data:/var/opt/mssql
      - ./data/sql1data/backup:/var/opt/mssql/backup
      environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=secretSecret1!
      ports:
      - "1433:1433"
