version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mssql:
    driver: ${VOLUMES_DRIVER}

services:

  ### MS SQL ###########################################
    mssql:
      image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
      container_name: mssql
      volumes:
      - ./data/mssql17-data:/var/opt/mssql
      - ./data/sql1data17/backup:/var/opt/mssql/backup
      environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=secretSecret1!
      ports:
      - "1433:1433"
