version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:

### PostgreSQL ###########################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
        - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend

  ### MS SQL ###########################################
    mssql:
      image: microsoft/mssql-server-linux:2017-latest
      container_name: mssql
      volumes:
      - ./data/mssql-data:/var/opt/mssql
      - ./data/sql1data/backup:/var/opt/mssql/backup
      environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=secretSecret1!
      ports:
      - "1433:1433"
